#!/usr/bin/bash
# Put this file in ~/.vim/bin/ . Will generate the template text
# when creating new journal entries using vim or vimwiki.
#
# Also put this at the end of your vimrc
#
#  au BufNewFile ~/vimwiki/diary/*.md :silent 0r !~/.vim/bin/generate-vimwiki-diary-template '%'
#
# But use appropraite paths and stuff.

date=$1
if [ -z $date ]
then
    date='today'
fi

daily add --no-edit -d "$date"
