#!/usr/bin/bash
# Put this file in ~/.vim/bin/ . Will generate the template text
# when creating new journal entries using vim or vimwiki.
#
# Also add this line to the end of your vimrc, then modify the pathing
# for your machine.
#
#  au BufNewFile ~/vimwiki/diary/*.md :silent 0r !~/.vim/bin/generate-vimwiki-diary-template '%'
#

date=$1
if [ -z $date ]
then
    date='today'
fi

# Pairs well --copy-previous
daily add --no-edit -d "$date"
